// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VGAppDb;

#nullable disable

namespace VGAppDb.Migrations
{
    [DbContext(typeof(VGAppDbContext))]
    [Migration("20250615150130_AddedTF2")]
    partial class AddedTF2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameUsers", b =>
                {
                    b.Property<string>("GamesPlayedName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsersThatPlayedId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("GamesPlayedName", "UsersThatPlayedId");

                    b.HasIndex("UsersThatPlayedId");

                    b.ToTable("GameUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReviewLikes", b =>
                {
                    b.Property<int>("LikedReviewsId")
                        .HasColumnType("int");

                    b.Property<string>("UsersThatLikedId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("LikedReviewsId", "UsersThatLikedId");

                    b.HasIndex("UsersThatLikedId");

                    b.ToTable("ReviewLikes");
                });

            modelBuilder.Entity("VGAppDb.Models.Game", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BackgroundUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Name = "Minecraft",
                            BackgroundUrl = "https://cdn2.steamgriddb.com/hero_thumb/ae93f6696a2a89b67aa6fb45092eded7.jpg",
                            Description = "Also try terraria!",
                            LogoUrl = "https://cdn2.steamgriddb.com/logo_thumb/90915208c601cc8c86ad01250ee90c12.png",
                            PosterUrl = "https://cdn2.steamgriddb.com/thumb/782c68199db381ee34a277258c28c89c.jpg",
                            PriceUSD = 20m,
                            ReleaseYear = 2011
                        },
                        new
                        {
                            Name = "DOOM",
                            BackgroundUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/379720/library_hero_2x.jpg?t=1573231983",
                            Description = "Fight like hell",
                            LogoUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/379720/logo_2x.png?t=1573231983",
                            PosterUrl = "https://cdn2.steamgriddb.com/thumb/775974bd62116bc3d3b2c51b04192f0c.png",
                            PriceUSD = 40m,
                            ReleaseYear = 2016
                        },
                        new
                        {
                            Name = "Undertale",
                            BackgroundUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/391540/library_hero.jpg?t=1579095961",
                            Description = "UNDERTALE! The RPG game where you don't have to destroy anyone. ",
                            LogoUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/391540/logo.png?t=1579095961",
                            PosterUrl = "https://cdn2.steamgriddb.com/thumb/14ec86d482ff9638392a061bfa431a1a.jpg",
                            PriceUSD = 20m,
                            ReleaseYear = 2015
                        },
                        new
                        {
                            Name = "DELTARUNE",
                            BackgroundUrl = "https://deltarune.com/assets/images/bg.gif",
                            Description = "DELTARUNE! The RPG game where your choices don't matter. ",
                            LogoUrl = "https://deltarune.com/assets/images/logo.png",
                            PosterUrl = "https://deltarune.com/assets/images/key-art.gif",
                            PriceUSD = 25m,
                            ReleaseYear = 2025
                        },
                        new
                        {
                            Name = "Grand Theft Auto V",
                            BackgroundUrl = "https://images.steamusercontent.com/ugc/11669731338331342254/D8FF2435AC1815F69543C8DEE34D15D52399A3DA/?imw=2048&imh=1152&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true",
                            Description = "Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.",
                            LogoUrl = "https://cdn2.steamgriddb.com/logo_thumb/e5b294b70c9647dcf804d7baa1903918.png",
                            PosterUrl = "https://cdn2.steamgriddb.com/thumb/86f045465e82c214dc5e68ba530546ba.jpg",
                            PriceUSD = 40m,
                            ReleaseYear = 2013
                        },
                        new
                        {
                            Name = "Red Dead Redemption 2",
                            BackgroundUrl = "https://cdn2.steamgriddb.com/hero_thumb/81e5f81db77c596492e6f1a5a792ed53.jpg",
                            Description = "Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age. ",
                            LogoUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/1174180/logo_2x.png?t=1671484934",
                            PosterUrl = "https://cdn2.steamgriddb.com/thumb/e746c3c588c51ad5efcc7125e3df662c.jpg",
                            PriceUSD = 40m,
                            ReleaseYear = 2018
                        },
                        new
                        {
                            Name = "Terraria",
                            BackgroundUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/105600/library_hero.jpg?t=1666290502",
                            Description = "Also try Minecraft!",
                            LogoUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/105600/logo_2x.png?t=1666290502",
                            PosterUrl = "https://images-ext-1.discordapp.net/external/ftJWBEe_E9ZCBdz6EEqxSXK4b5r_9zFTEimtI9KII7Q/https/cdn2.steamgriddb.com/thumb/301c8008a981254f98950cebef344b58.jpg?format=webp",
                            PriceUSD = 5m,
                            ReleaseYear = 2011
                        },
                        new
                        {
                            Name = "Counter-Strike",
                            BackgroundUrl = "https://cdn2.steamgriddb.com/hero_thumb/1be3614ec5d67a9fe3fd389516f369ea.jpg",
                            Description = "Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. ",
                            LogoUrl = "https://cdn2.steamgriddb.com/logo_thumb/13d429db192fbc7b5cabf9b936cf78e1.png",
                            PosterUrl = "https://cdn2.steamgriddb.com/thumb/6bf8cff2494ff41052ac8474df638cdb.jpg",
                            PriceUSD = 5m,
                            ReleaseYear = 2000
                        },
                        new
                        {
                            Name = "Team Fortress 2",
                            BackgroundUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/440/library_hero.jpg?t=1745368576",
                            Description = "After 9 years in development.",
                            LogoUrl = "https://shared.steamstatic.com/store_item_assets/steam/apps/440/logo.png?t=1745368576",
                            PosterUrl = "https://cdn2.steamgriddb.com/thumb/2eaa17f7324d93370a43a7b8d55d038e.jpg",
                            PriceUSD = 0m,
                            ReleaseYear = 2009
                        });
                });

            modelBuilder.Entity("VGAppDb.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GameName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("PublicationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GameName");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VGAppDb.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GameUsers", b =>
                {
                    b.HasOne("VGAppDb.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesPlayedName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGAppDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersThatPlayedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VGAppDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VGAppDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGAppDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VGAppDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewLikes", b =>
                {
                    b.HasOne("VGAppDb.Models.Review", null)
                        .WithMany()
                        .HasForeignKey("LikedReviewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VGAppDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersThatLikedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VGAppDb.Models.Review", b =>
                {
                    b.HasOne("VGAppDb.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameName");

                    b.HasOne("VGAppDb.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VGAppDb.Models.Game", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VGAppDb.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
